language: node_js

node_js:
  - 12

services:
  - docker

install:
  - echo "nothing installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed luannm9/udagram-api-feed:v1
  - docker tag udagram-api-user luannm9/udagram-api-user:v1
  - docker tag udagram-frontend luannm9/udagram-frontend:v1
  - docker tag reverseproxy luannm9/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push luannm9/udagram-api-feed:v1
  - docker push luannm9/udagram-api-user:v1
  - docker push luannm9/udagram-frontend:v1
  - docker push luannm9/reverseproxy:v1
